### PR TITLE
feat(grafana): Dynamic dashboard navigation

### LINKED ISSUE #69: Make grafana 'cluster overview' dashboard dynamic
Current grafana 'cluster overview' dashborard has a  hard coded list of components.
For instance, if hbase is not installed on cluster, the cluster overview shows a hbase failure. Also, a 'hbase' dashboard is provisionned on grafana. This dashboard is obviously in error.
Proposed evolutions :
 - Make 'cluster overview' dashboard dynamic
 - Filter copied dashboards by installed services
 - Define 'cluster overview' as home dashboard

### PR DESCRIPTION
**Pull request by giem-git**
#### Which issue(s) this PR fixes

Fixes #69

#### Agreements

- [x] I hereby declare this contribution to be licensed under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0).
- [x] I hereby agree to grant [TOSIT](https://www.tosit.io/) a copyright license to use my contributions.

### CODE REVIEW

**Comment by kpgtek** [comment]
I think there are ```EOL``` missing in Dashboards ```.json``` files.

**Comment by kpgtek** [comment]
As discussed with @giem-git, "Python service components" dashboard is to be removed,

**Comment by giem-git** [comment]
> I think there are `EOL` missing in Dashboards `.json` files.

Just fixed this

**Comment by giem-git** [comment]
> As discussed with @giem-git, "Python service components" dashboard is to be removed,

The file has been removed

**Review by kpgtek — APPROVED** [review]

**Pull request merged**
